### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by JosseVanDelm**
I am not a lawyer

inspired by https://github.com/xdslproject/xdsl/blob/main/LICENSE

### CODE REVIEW

**Review by AntonLydike — APPROVED** [review]

**Comment by AntonLydike** [comment]
Just know that you in theory need everyone who contributed code to accept the relicensing. Shouldn't be too difficult?

**Comment by JosseVanDelm** [comment]
@JonasCrols @jorendumoulin @tobiasgrosser can you please approve :smile:

**Comment by tobiasgrosser** [comment]
Approved.

**Review by jorendumoulin — APPROVED** [review]
I hereby authorize the proposed modification to the licensing

**Review by JonasCrols — APPROVED** [review]
I Approve of the changes made to the license

**Comment by JosseVanDelm** [comment]
Thank you all for the prompt reply :dancing_men:

**Pull request merged**
