### PR TITLE
Add snax.mcycle op

### PR DESCRIPTION
**Pull request by JosseVanDelm**
This PR adds an operation that adds a utility mcycle operation to the snax dialect.
This is useful to split up traces in multiple sections

### CODE REVIEW

**Comment by AntonLydike** [comment]
I wonder what it would take to re-use the lowerings already in xdsl for this?

**Comment by AntonLydike** [comment]
After talking to Sasha, it does not. They implement it in their C wrapper code.

**Review by AntonLydike — APPROVED** [review]
This feels a bit too hacky even for my taste, but I guess the show must go on...

**Comment by JosseVanDelm** [comment]
> I wonder what it would take to re-use the lowerings already in xdsl for this?

Oops I did not consider this.

> This feels a bit too hacky even for my taste, but I guess the show must go on...

Not sure what you mean by this. Calling into C code for this purpose seems a lot hackier in my opinion?
I guess right now it is a bit basic, but it should serve it's purpose just fine I think?

**Pull request merged**
