### PR TITLE
benchmark: Add benchmark system

### PR DESCRIPTION
**Pull request by JosseVanDelm**
This PR implements various things that ultimately allows you to run and plot various benchmarks:
* Fixes to #164 . It replaces it with a hardcoded operation that writes to the zero register. The result of this can not be used in the program, but acts as a signal to the postprocessing gen_trace.py script
* Adds a benchmark system under the `benchmark` package that allows to run from python what you would typically run by hand in the terminal
* Parameterizes the `tiled_add` benchmark (with a _super!_ simple and _now correct!_ `sed` statement) with makefile arguments
* Adds a plotting script that traces the various sections introduced in the program with the `snax_mcycle` operation.

### CODE REVIEW

**Review by AntonLydike — APPROVED** [review]
Nice! Will try to run locally as well, but glad to see automatic plotting making it in!

**Comment by JosseVanDelm** [comment]
@AntonLydike I refactored a bunch of things. Please rereview!

**Comment by JosseVanDelm** [comment]
@jorendumoulin also interested on your thoughts on this!

**Comment by JosseVanDelm** [comment]
Waiting for the container to get there https://github.com/KULeuven-MICAS/snax_cluster/actions/runs/9775753913/job/26986835028

**Pull request merged**
